# vim: st=2 sts=2 sw=2 et:

sudo: false

notifications:
  email: false

cache:
  pip: true
  directories:
    - download-cache

env:
  global:
    - ARGON2_VERSION=20161029
    - ARGON2_DIR=$HOME/argon2
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"
    - LUA="lua 5.3" ARGON2_VERSION="HEAD"

matrix:
  fast_finish: true
  allow_failures:
    - env: LUA="lua 5.3" ARGON2_VERSION="HEAD"

before_install:
  - mkdir -p download-cache
  - pushd download-cache
  - if [ ! -d phc-winner-argon2 ]; then git clone https://github.com/P-H-C/phc-winner-argon2.git; fi
  - popd
  - cp -R download-cache/phc-winner-argon2 $ARGON2_DIR
  - pushd $ARGON2_DIR
  - if [ "$ARGON2_VERSION" != "HEAD" ]; then git checkout $ARGON2_VERSION; fi
  - make > build.log 2>&1 || (cat build.log && exit 1)
  - make test > build.log 2>&1 || (cat build.log && exit 1)
  - if [ "$ARGON2_VERSION" != "HEAD" ]; then ln -s libargon2.so libargon2.so.0; fi
  - popd
  - pip install --user hererocks cpp-coveralls > build.log 2>&1 || (cat build.log && exit 1)
  - hererocks lua_install -r^ --$LUA > build.log 2>&1 || (cat build.log && exit 1)
  - export PATH=$PATH:$PWD/lua_install/bin
  - luarocks install busted > build.log 2>&1 || (cat build.log && exit 1)

install:
  - luarocks make CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage" ARGON2_INCDIR=$ARGON2_DIR/include ARGON2_LIBDIR=$ARGON2_DIR
  - make clean

script:
  - busted -v -o gtest --repeat 3 spec

after_success:
  - coveralls -b . -r . -i ./src
