sudo: false
notifications:
  email: false
env:
  global:
    - LUAROCKS_VERSION=2.2.2
    - LUA_DIR=$HOME/lua
    - LUAJIT_DIR=$HOME/luajit
    - LUAROCKS_DIR=$HOME/luarocks
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit-2.0
    - LUA=luajit-2.1
before_install:
  - bash .ci/setup_lua.sh
  - export PATH=$LUA_DIR/src:$LUAJIT_DIR/bin:$LUAROCKS_DIR/bin:$PATH
install:
  - luarocks install busted
  - luarocks make argon2-*.rockspec
  - make clean
script:
  - make test
